### PR TITLE
Added kubeclient to context for new adapter creation

### PR DESCRIPTION
**Pull request by Cali0707**
Fixes the failing integration tests

## Proposed Changes

- Add the kubeclient into the context used to create the new adapter in the Update function

### CODE REVIEW

**Comment by Cali0707** [comment]
/hold
I'll unhold when the integration tests pass

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by Cali0707** [comment]
/unhold
All the tests passed

**Comment by creydr** [comment]
Thanks for fixing @Cali0707

**Pull request merged**
